version: '3.3'

services:

  mongodb:
    container_name: mongo-backend
    image: mongo
    volumes:
      - data:/data/db
  back:
    container_name: back-container
    restart: always
    build: ./back
    ports:
      - 3001:3001
    volumes:
      - logs:/app/logs
      - ./back:/app
      - /app/node_modules
    environment:
      - MONGO_URI= mongodb+srv://DevopsUsername:DevopsPassword@cluster0.5ngkur4.mongodb.net/test
    depends_on:
      - mongodb

  front:
    container_name: front-container
    restart: always
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - back
volumes:
  data:
  logs:

  