---
- name: Install packages
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install docker
      yum:
        name: docker
        state: latest

    - name: start docker
      service:
        name: docker
        state: started

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present