apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: "rgv176/devopsragavi-back"
        ports:
         - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb+srv://DevopsUsername:DevopsPassword@cluster0.5ngkur4.mongodb.net/test

      
