name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker-compose
      run:  docker-compose build
    - name: Check running containers
      run: docker ps -a
    - name: Run docker Docker-compose
      run: docker-compose up -d
    - name: Test
      run: docker run --network container:front-container appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/




