name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker-compose
      run:  docker-compose build
    - name: Check running containers
      run: docker ps -a
    - name: Run docker Docker-compose
      run: docker-compoe up
    - name: test
      run: http://localhost:3000/




